### ISSUE TITLE
detect.sh issue with Raspberry Pi Zero 2

### ISSUE THREAD

**Issue by sliverx** [SWiT/gpihdmiout#2]
I recently got a Zero 2 running in my GPi Case: The enable and disable scripts work on it but detect.sh couldn't tell when the HDMI cable was disconnected on boot after enabling HDMI out: 

The Zero 2 reports a value of 0x40000 for the $TVCODE variable Line 25 elifs against rather than 0x40001: Changing the value allows the script to work as expected.

**Comment by SWiT** [comment]
Thanks for the report.  I'll add Zero 2 support later tonight.  I got hung up trying to manually install Retropie on my Zero 2 with the 10/30/2021 32bit RPiOS release. SDL2 wasn't installing in under the Basic Install. I  got the Super Retroboy Z2 distro to boot so I'll use that and update the script tonight.  What image are you using?

**Comment by sliverx** [comment]
I'm running a direct dd flash of the Pi3 Retropie weekly build from 11/7 using the Safe Shutdown script, your script and manual edits to /boot/config.txt and /etc/asound.conf to make sound work and downmix to mono, respectively.

**Comment by SWiT** [comment]
It should work now at 1080p60.  I still need to check if the TV state codes stay the same at various lower resolutions and refresh rates.
