### ISSUE TITLE
Pi Zero 2 Sound

### ISSUE THREAD

**Issue by Dark98** [SWiT/gpihdmiout#4]
This breaks sound through the case with a Zero 2 After Using it due to the audio config being different between the two devices

**Comment by sliverx** [comment]
The copy of /boot/config.txt that makes audio work on your device should also be put under /boot/GPi_Case_Patch/patch_files/ as well.

The HDMI script is restoring the config.txt file located under here to /boot, so if it isn't the same file it gets replaced with a "clean" copy that ships with the Retroflag patch (Until/if they update it to support the Zero 2).

**Comment by SWiT** [comment]
Sliverx is correct. Any modifications to /boot/config.txt like overclocking, audio tweaks, etc. also needs to be done to /boot/GPi_Case_Patch/patch_files/config.txt and /boot/GPi_Case_patch/original_files/config.txt
